var bios =[
/*pedro*/{
	"name":"Pedro",
	"img":"images/bios/pedro.jpg",
	"title":"Former poultry worker",
	"text":"<p>When Pedro arrived in the US from Guatemala, he worked in a furniture company-- until it relocated. The only other employer in the area was the poultry plant. Pedro believes the lack of options allows the company to take advantage of people. When supervisors want workers to hurry up, they yell, “There are a hundred applications waiting to come in.”</p><p>Pedro worked the night shift, where workers stayed until all the chickens were processed--often 12 hours at a stretch. Their knives were sharpened during breaks. And when the “knives got dull, you had to do all the motions harder and harder.”</p><p>These forceful motions led to problems with Pedro’s hands. “I got to the point that I used to get triple-X gloves, and they wouldn’t fit because my hands were so swollen.”  </p><p>Pedro informed the plant managers about his injuries, and requested a different position. He also asked the company to consider workers’ compensation and allow him to see a doctor. They refused every request, and threatened to fire him. </p><p>After four years, Pedro was fired with little explanation. He believes he was dismissed because he was trying to educate others about their rights. He is currently unemployed.</p>",
	"quote":"“Is it worth my health, losing a limb, losing my arms for some little bit of money and not be able to hug and carry my child, or my grandkids?”"
},
/*chart*/{
	"name":"",
	"img":"images/Oxfam-Poultry_reported-workplace-injuries-charts.png",
	"title":"",
	"text":"",
	"quote":"Lorem Ipsum Dolor"
},
/*Isabella*/{
	"name":"Isabella",
	"img":"images/bios/isabella.jpg",
	"title":"Former poultry worker, Case Farms",
	"text":"<p>Isabella says that her time working in the poultry industry “opened her eyes” to discrimination, racism, and the rights of workers.</p><p>Isabella left Guatemala to work with her brothers in a poultry plant in North Carolina. After a while, she managed to bring her three children to join her. “I came here because I wasn't able to offer my kids what was best for them, and I thank God for giving me … this opportunity.”</p><p>Since she was supporting her family back home as well as her children, Isabella struggled to earn enough. In addition to working full-time at the plant, she started her own business cooking meals for people in town.</p><p>For nearly eight years, she worked on the line. Supervisors regularly denied bathroom breaks to workers—even to pregnant women. The plant was extremely cold and the chemicals were overwhelming. She developed a problem with her shoulder that still limits her movement.</p><p>She was fired one day out of the blue. The company said that they had suddenly noticed that her documentation was not in order. Isabella believes they fired her because she had become more aware of her rights, and was standing up for herself.</p>",
	"quote":"“I stopped being afraid… I became more aware of my rights. In the end, I think that advocating for my rights is what got me fired.”"
},
/*Roberto*/{
	"name":"Roberto",
	"img":"images/bios/roberto.jpg",
	"title":"Former poultry worker, Simmons",
	"text":"<p>After moving to Arkansas from Mexico, Roberto spent two years as a chicken “hanger” on the line; thousands of times a day, he lifted birds and inserted their feet into shackles. </p><p>After an injury, he struggled for months. The plant medical staff “just kept prescribing more medicine and told me to increase the dosage and use it more often.” Eventually, the doctor said that working so long without proper medical care had led to carpal tunnel syndrome in both hands. </p><p>Roberto kept going to work, hoping to switch positions so he could get relief for his strained muscles, but, “with my injuries, I couldn’t do my job well. They gave me warnings. I was reprimanded, disrespected and offended.”</p><p>He finally had surgery on both hands, but is still in pain and not strong enough to work. This leaves him in a desperate position:</p><p>“When you get sick, you can barely get enough for food; you cannot support yourself. … My mother has had three surgeries; … she is very old and cannot work, and is depending on me. And that is what gets me. Right now I can’t fend for myself—never mind help her, not even her basic necessities. ... It causes me great despair.”</p>",
	"quote":"“I … want them to value the workers, not to trample their rights—not only the animals’.”"
},
/*chart*/{
	"name":"",
	"img":"images/Industry_False_Claims.jpg",
	"title":"",
	"text":"<p>In response to myriad reports and surveys about shocking injury rates, the poultry industry usually responds with the chart at left. The National Chicken Council created it to illustrate what they call “the enormous progress the industry has made in improving safety for its workforce” in the past 20 years.</p><p>The situation is far more complicated than the chart would lead you to believe. The dramatic drop in injuries pictured does not only reflect safety improvements; it is largely due to other factors. Workers are still getting hurt, but those injuries are not getting reported.</p><p>Two major factors make it possible to illustrate the “drop” in injury rates:</p><ol><li><strong>The rules about reporting incidents have changed.</strong> In 2002, a new form eliminated the column for repetitive strain injuries. This new form dramatically (and falsely) lowered the reporting of the incident rate.</li><li><strong>Incidents are underreported.</strong> Plants use a variety of tactics to discourage workers, supervisors, and medical personnel from reporting incidents.</li></ol><p>These tactics may be positive (rewards) or negative (disciplinary actions). The result is that many workers simply do not report injuries or seek care. One survey reported that 66 percent of workers were scared or reluctant to report injuries; 78 percent attributed this reluctance to fear of being fired.</p>",
	"quote":"“An impressive, but fictitious improvement in plant safety” – Human Rights Watch",
	"caption":"Source: National Chicken Council, “Poultry Industry Continues to Improve Worker Safety Record,” November 8, 2012, http://www.nationalchickencouncil.org/poultry-industry-continues-to-improve-worker-safety-record/."
},
/*Albious */{
	"name":"Albious Latior",
	"img":"images/bios/albious.jpg",
	"title":"Marshallese Outreach Coordinator, Northwest Arkansas Workers’ Justice Center",
	"text":"<p>Albious Latior, originally from the Marshall Islands in the South Pacific, works with poultry workers through the Northwest Arkansas Workers’ Justice Center in Springdale, AR. When Marshallese natives arrive in the US, they are eager to work and typically head to poultry plants in Arkansas. As a result, Arkansas has the largest population of Marshallese outside their own country </p><p>Because of a complex history with the US (the US government conducted nuclear tests in the Islands from 1946-58 and radioactive fallout rendered some islands uninhabitable), the Marshallese come to the US as legal residents. Latior explains, “They dropped the bombs and practiced at our island ... And we see that everything is radiation. So we have to find somewhere to go to live—to raise a good family. So we decided to go to America.”</p><p>While the Marshallese may live, work, and study in the US, they must pay also taxes and are denied benefits such as Medicare and Medicaid. </p><p>Latior is concerned that new Marshallese workers are vulnerable to exploitation in the workplace. Because “everything is new to them,” the poultry companies can take “advantage of them.” <p>",
	"quote":"“What is happening at the poultry [plants] right now is really sad… [The workers] don't know that they have the right to talk about how they're mistreated at work.”"
},
/*Mary */{
	"name":"Mary Goff",
	"img":"images/bios/mary.jpg",
	"title":"Former staff attorney, Legal Aid of Arkansas",
	"text":"<p>As a staff attorney at Arkansas Legal Services Partnership, Mary Goff met hundreds of poultry workers who were struggling to survive the industry intact, while taking care of their families.</p><p>Workers had many concerns about violations of their rights. Among them:</p><ul><li>Injuries: “If a person gets injured on the job and mysteriously gets fired not too long after, that seems like a problem.”</li><li>Language barriers: “Language has been dubbed a proxy for national origin, so if someone's being discriminated against based on their language it can mean that they're being discriminated against on the basis of national origin.”</li><li>Lack of transparency: “Mysterious work rules, disciplinary actions that make no sense.”</li><li>Sexual discrimination, and discrimination based on national origin, religion, disability.</li></ul><p>Difficulty accessing unemployment benefits: “not only are they wrongfully terminated, but they're left without any source of income while they scramble to find another job.”</p>",
	"quote":"“I appreciate the financial implications of running a big business and trying to grow the economy.  But I appreciate more that these people are humans. They're our brothers; they're our sisters, our mothers, our fathers. And we should move towards making their lives bearable and making work an experience that they want to go back to--not something that they suffer through.”"
},
/*Spencer */{
	"name":"Spencer Lo",
	"img":"images/bios/spencer.jpg",
	"title":"Worker advocate, Western North Carolina worker's center",
	"text":"<p>Like many Hmong immigrants, Spencer Lo moved from Laos to North Carolina to work in the furniture industry. He says the weather reminds them of home, and the jobs are steady. Lo estimates that the Hmong population in North Carolina is about 20,000. </p><p>When the furniture factories closed, many of the workers felt stranded—especially because, Lo says, many are uneducated and speak little English. So a large percentage of the Hmong turned to the poultry plants in Morganton and Wilkesboro. </p><p>Lo admits that he couldn’t handle the speed of the line and the slippery plant conditions. Today, he works as an organizer and advocate for poultry workers from Laos, the Marshall Islands, and Latin America.  </p><p>He sums up the conditions for many poultry workers from other countries: “They…[are] working too fast” and have “ no chance to go bathroom.” He concludes, “And they work all the time. The lines are very, very fast for them, but they get little pay. That doesn't make sense.”</p>",
	"quote":"“We need to care about the low-wage workers.  They're working too fast.”"
},
/*Jose */{
	"name":"Jose",
	"img":"images/bios/jose.jpg",
	"title":"Former poultry worker, Pilgrim’s",
	"text":"<p>Jose was drawn to a Pilgrim’s poultry plant when he saw an ad in a newspaper in Puerto Rico. A labor contractor promised good wages and cheap accommodations. Jorge came to the US for a better future, but he found that most of the promises were, in the words of his plant supervisor, “una mentira” (a lie). </p><p>Increasingly, poultry companies are using labor contractors to solve workforce problems. Unfortunately, contractors offer few benefits to workers. </p><p>Jose found he was sharing an apartment with several other workers. His bed reeked of urine, and his rent was over 40% more than advertised. In addition, the contractor charged $20 a week for gas (for transportation to work). And the hourly wage was $8.40 – not the $11.25 he’d been promised. </p><p>Jose found work on the line exhausting. When his hand and back began to ache, plant personnel told him that the pain would go away, and gave him unlabeled pain pills. He reported that racism and harassment were commonplace. When he spoke up, he was told, “If you don’t like it, you can go home.” </p><p>Although Jose was never late or absent, and completed all his work, he was eventually fired—and evicted from his apartment. </p>",
	"quote":"“I would go to see the nurse almost every day. She would give me pills … and send me back to the line. But the pain never stopped.”"
},
/*chicken */{
	"name":" ",
	"img":"images/Oxfam-Poultry_chicken_parts.png",
	"title":" ",
	"text":"<p><strong>Line loaders</strong> remove the cages and unload the chickens onto conveyor belts.</p><p><strong>Hangers</strong> lift the birds from the belt one by one, and insert the feet into continuously moving shackles overhead.</p><p><strong>Automated stages:</strong> In most plants, the hanging birds are stunned, then decapitated by machine. The carcasses go through scalding tanks, then machines beat the feathers off. The head, feet, and tail are removed to allow automated evisceration; the carcasses are washed and chilled.</p><p><strong>Cone Line Feeders</strong> remove the carcasses from the hanging line and insert them onto cones on a conveyor belt.</p><p><strong>Wing Cutters</strong> lift each wing up, then use scissors to cut the wing off the carcass.</p><p><strong>Leg/Thigh Cutters</strong> use knives, scissors, and/or saws to remove legs and thighs.</p><p><strong>Back/Breast Separators</strong> tug and cut to separate breast and tenders from the back of the bird.</p><p><strong>De-Boners/Trimmers/Cleanup Workers</strong> use knives to remove bone (or fat or skin) from various pieces of the bird, to carve out a &ldquo;meat only&rdquo; product.</p><p><strong>Packagers</strong> place product in a package, and into a shipping box.</p><p><strong>Miscellaneous Processors</strong> produce such things as nuggets, sausages, seasoned entrees</p>",
	"quote":"How many people are needed to process a chicken?",
	"caption":"Source: US Poultry and Egg Association, Poultry Processing Curriculum, page 9, http://uspoultry.org/educationprograms/PandEP_curriculum/documents/pdfs/lesson9/poultryprocessingver3.pdf"
},
/*text modal */{
	"text":"<p>We each decide what matters to us when we choose our food. We may exclude meat or eat only organic, or vegan, or fair trade.</p><p>The choice is yours, but you deserve to know enough to make informed choices. If you’re going to eat chicken, you need to consider what goes on behind the scenes; how not only the animals but workers are treated in raising and processing our food.</p><p>We believe the industry exploits workers by treating them as a disposable part of the production process.</p><p>But we also know that this can change. The poultry industry can implement changes that will make it possible to work on the processing line without suffering. Big Poultry can produce healthy food ethically and profitably.</p><p>Any type of work can have dignity and merit. Poultry workers do vital jobs that bring food to our tables. These jobs are arduous, but they don’t need to be dangerous and undignified.</p><p>What we’re asking is that these jobs enable hard-working people to live well, support their families, and enjoy the bounty of the industry.</p>"
},
/*text modal */{
	"text":"<p>The US government’s Occupational Health and Safety Administration (OSHA) openly acknowledges that the poultry industry poses dangers for workers every day.</p><p>However, the agency does not have specific safety standards for the poultry industry; and it is woefully understaffed and underfunded. The agency has enough personnel to inspect just 1 percent of all workplaces in the US each year.</p><p>Even when OSHA does inspect a plant and finds violations, penalties are weak and fines low. It may be cheaper for a company to run an unsafe plant and pay minuscule fines, than to take measures to protect workers.</p><p>In 2014, the average OSHA penalty for a serious violation was $1,972. A former policy director of OSHA commented, “Even when an inspector discovers life-threatening violations, the penalties are shockingly small.”</p><p>In one example, in 2011, a Perdue plant in Virginia was found to have committed 12 safety violations, including six that OSHA classified as “serious,” yet the company was only fined $6,000, which was negotiated down to just $4,000.</p><p>In another example, OSHA recently named Pilgrim’s to their “Severe Violator” program, which is designed for companies that have repeatedly violated health and safety laws. Yet despite its record, Pilgrim’s has faced only $158,000 in fines since 2011, a miniscule amount for a company with over $700 million in profits in 2014 alone.</p>"
},/*bacilio*/{
	"name":"Bacilio",
	"img":"images/bios/bacilio.jpg",
	"title":"Former poultry worker and worker’s advocate",
	"text":"<p>Basilio Castro is from an indigenous community in Guatemala. During the civil war, his mother and three uncles were killed. His family relocated, but struggled “to get ahead financially.” Eventually Basilio came to the US and “started working in the chicken processing plant.”</p><p>After injuring himself on the job, Bacilio became “aware that the company did not respect the rights of employees.” He saw a co-worker lose a finger and another fall on a slick floor, breaking her hip. But it was the treatment of his pregnant co-worker that “shocked” him. “I felt that those harsh words could be directed at my mother, or sister. ... I told the supervisor what he was doing was wrong.”</p><p>Bacilio sought help. “I went to a Catholic church and they told me about a worker’s center.” He began taking trainings and volunteering there.</p><p>“Today,” he reports, “I am a staff member of the Worker’s Center.” Their mission is to empower workers, helping them overcome their fear, because—as Bacilio assures them—“In this country, all workers have rights.”</p>",
	"quote":"“I was working next to a lady who was eight months pregnant. She needed to go to the bathroom and asked for permission. An hour passed, then two. She asked again. The supervisor said, ‘Sorry, lady, but no one can cover for you. Hold it awhile more.’ Finally the woman wet her pants and began to cry.”"
},/*myrna*/{
	"name":"Myrna",
	"img":"images/bios/myrna.jpg",
	"title":"poultry worker, Simmons",
	"text":"<p>Myrna traveled from Mexico to the US as a young woman. Over the course of 12 years trimming chicken at a Simmons plant in Arkansas, she witnessed a lot of injustice, but was afraid to speak out for fear of losing her job.</p><p>“We have our family to support. We have kids—who are what we love the most in this world. So it’s a little difficult … to … say they treat people like this and like that; it’s difficult to talk.”</p><p>After years of trimming chicken pieces, her hand started hurting. “I went to the infirmary and I told them my hand hurt a lot from top to bottom. Every day I woke up with my hand swollen and in pain.”</p><p>When she requested a change in her position, “The manager told me no, that I am doing my job very well where I am, and that he doesn’t have anybody to replace me.” On the first occasion, she accepted this answer, but she made subsequent requests to be moved to another position so she could rest the affected muscles. Each time, her requests were flatly denied. She says, “It didn’t just happen once, but again and again and again.”</p>",
	"quote":"“This is an injustice what they are doing. With my hands I touch my kids, with my hands I earn my food.”"
}
];
